# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiharrasment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='polarity',
            new_name='is_harrassing',
        ),
    ]
